//test case for exception being caught
public class CatchException
{
    public void someFun()
    {
        try
        {
        	//stuff
        }
        catch (Exception e)
        {
        	//stuff
        }
    }
}