
public class TestResource2 {
	public void testFunction() {
		try {
			
		}
		catch (Exception e) {
			
		}
		try {
			
		}
		catch (Exception e) {
			
		}
	}
}
