//test case for exception being caught
public class ThrowsException
{
    public void someFun() throws Exception
    {

    }
}